# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jenniferparsons
ko_fi: pixelpaperyarn 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
