# These are supported funding model platforms

github: jenniferlynparsons
patreon: jenniferparsons
ko_fi: pixelpaperyarn 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
